version: "3.8"

services:
  main_service:
    image: golang:latest
    build:
      context: .
      dockerfile: ./main_service/Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - auth_db
    env_file:
      - .env

  auth_db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGR_USR}
      POSTGRES_PASSWORD: ${POSTGR_PASSWORD}